project:
  type: website

website:
  navbar:
    logo: assets/logo_tillac.png
    background: primary
    search: false
    collapse: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: false



